# Generated by Django 3.2.9 on 2022-02-05 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cutomer_name', models.CharField(max_length=20)),
                ('phone_number', models.IntegerField()),
                ('customer_email', models.CharField(max_length=30)),
            ],
        ),
    ]
