# Generated by Django 3.2.9 on 2022-02-05 09:47

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customers',
            name='id',
        ),
        migrations.AddField(
            model_name='customers',
            name='customer_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
